In [1]:
import pandas as pd 
import numpy as np

#1

N = 24000
data = pd.read_csv('data/data_000637.txt', nrows = N)
display(data)

#2
max_bx = data['BX_COUNTER'].max() + 1
print("estimation number: ", max_bx)

#3
bx_with_max_orbit = data.loc[data['ORBIT_CNT'] == max(data["ORBIT_CNT"])]
bx_with_min_orbit = data.loc[data['ORBIT_CNT'] == min(data["ORBIT_CNT"])]

tdc_with_max_bx = bx_with_max_orbit.loc[bx_with_max_orbit['BX_COUNTER'] == max(bx_with_max_orbit["BX_COUNTER"])]
tdc_with_min_bx = bx_with_min_orbit.loc[bx_with_min_orbit['BX_COUNTER'] == min(bx_with_min_orbit["BX_COUNTER"])]

initial_ns = (min(data["ORBIT_CNT"]) * max_bx + min(bx_with_min_orbit["BX_COUNTER"])) * 25 + min(tdc_with_min_bx["TDC_MEAS"]) * 25/30                                                                                                 
data['NS_PASSED'] = ((data['ORBIT_CNT'] * max_bx + data['BX_COUNTER']) * 25 + data['TDC_MEAS'] * 25 / 30) - initial_ns
data
#4

max_tdc = max(data["TDC_MEAS"]) + 1

dif_orbit = max(data["ORBIT_CNT"]) - min(data["ORBIT_CNT"])

bx_with_max_orbit = data.loc[data['ORBIT_CNT'] == max(data["ORBIT_CNT"])]
bx_with_min_orbit = data.loc[data['ORBIT_CNT'] == min(data["ORBIT_CNT"])]

dif_bx = max(bx_with_max_orbit["BX_COUNTER"]) - min(bx_with_min_orbit["BX_COUNTER"])

tdc_with_max_bx = bx_with_max_orbit.loc[bx_with_max_orbit['BX_COUNTER'] == max(bx_with_max_orbit["BX_COUNTER"])]
tdc_with_min_bx = bx_with_min_orbit.loc[bx_with_min_orbit['BX_COUNTER'] == min(bx_with_min_orbit["BX_COUNTER"])]

dif_tdc = max(tdc_with_max_bx["TDC_MEAS"]) - min(tdc_with_min_bx["TDC_MEAS"])

if(dif_tdc < 0):
    dif_bx = dif_bx - 1
    dif_tdc = dif_tdc + max_tdc

print(dif_orbit, " orbit ")
print(dif_bx, " bx")
print(dif_tdc, " tdc")

print(((dif_orbit*max_bx)+dif_bx)*25*1e-9 + dif_tdc * 25/30*1e-9, " seconds")
#5




noisy_channels = data.groupby(by=["TDC_CHANNEL"]).size().sort_values(ascending = False).head(3)
noisy_channels
#6
non_empty_orbits = data.groupby('ORBIT_CNT')
print("Number of non-empty orbits: ", len(non_empty_orbits))

#7


tdc_channel_139 = data[data['TDC_CHANNEL'] == 139].groupby('ORBIT_CNT')
print("When TDC_CHANNEL = 139 Number of unique orbits =  ", len(tdc_channel_139))
#8


fpga_0 = data[data['FPGA']== 0].groupby('TDC_CHANNEL').size().reset_index(name='COUNT')
print(fpga_0)
fpga_1 = data[data['FPGA']== 1].groupby('TDC_CHANNEL').size().reset_index(name='COUNT')
print(fpga_1)

       HEAD  FPGA  TDC_CHANNEL   ORBIT_CNT  BX_COUNTER  TDC_MEAS
0         1     0          123  3869200167        2374        26
1         1     0          124  3869200167        2374        27
2         1     0           63  3869200167        2553        28
3         1     0           64  3869200167        2558        19
4         1     0           64  3869200167        2760        25
...     ...   ...          ...         ...         ...       ...
23995     1     1           12  3869200406        1038        19
23996     1     0          139  3869200406        1039         0
23997     1     1           18  3869200406        1037        29
23998     1     0           49  3869200406        1037        17
23999     1     1           15  3869200406        1038         6

[24000 rows x 6 columns]

estimation number:  3564
239  orbit
-1336  bx
4  tdc
0.021261503333333338  seconds
Number of non-empty orbits:  240
When TDC_CHANNEL = 139 Number of unique orbits =   240
     TDC_CHANNEL  COUNT
0              1     14
1              2     25
2              3     19
3              4     26
4              5     33
..           ...    ...
113          121    119
114          122    123
115          123    334
116          124    315
117          139   1409

[118 rows x 2 columns]
     TDC_CHANNEL  COUNT
0              1    515
1              2    574
2              3    429
3              4    477
4              5    291
..           ...    ...
121          125     10
122          126     10
123          127     22
124          128     25
125          139    610

[126 rows x 2 columns]