# **Exercise 1**

In [ ]:
import numpy as np
import pandas as pd
import random 
import csv
import itertools

In [ ]:
f = open("data_int.txt", "w")
listofnums = []
n = random.randint(1,1000)
for i in range(0,n):
  listofnums.append(random.randint(0,10000))
f.write(str(listofnums)) 
f.close()

!cat data_int.txt

[2516, 5153, 6114, 6462, 8053, 8582, 8198, 6863, 7823, 5468, 6126, 7316, 1995, 655, 7628, 5419, 3176, 9708, 5766, 7017, 6405, 2830, 2698, 6127, 677, 2441, 8015, 6698, 9224, 8154, 9147, 3251, 8798, 62, 9201, 4650, 9040, 3783, 8063, 4267, 3183, 3297, 7948, 30, 4029, 431, 9610, 5959, 2095, 3010, 3778, 5417, 9581, 2618, 1408, 3003, 3108, 4273, 5126, 3011, 7925, 9399, 9051, 4116, 5573, 3828, 6162, 4449, 5088, 1217, 8280, 8820, 1095, 909, 5426, 1618, 6332, 6616, 9156, 7182, 368, 6974, 6756, 4031, 2837, 5404, 3363, 9410, 83, 7841, 3637, 7290, 5012, 2588, 7620, 7384, 8853, 575, 6444, 7061, 1731, 1641, 4076, 1346, 5613, 2211, 2040, 1632, 3908, 1783, 2619, 477, 3114, 5005, 1790, 1514, 8622, 7427, 70, 1671, 1305, 7307, 6886, 1636, 9842, 9650, 8052, 8842, 610, 1556, 6975, 7686, 6164, 5336, 9771, 3999, 2320, 2215, 6588, 1887, 9300, 92, 3329, 1827, 4738, 9989, 3909, 8176, 9602, 5296, 8957, 8104, 1615, 7861, 4746, 3579, 7782, 4931, 1686, 7436, 2157, 1411, 8368, 1092, 3241, 6681, 0, 4923, 9298, 4478, 7416, 3096, 114, 4366, 9546, 1966, 9456, 5367, 7950, 9115, 8001, 2031, 7420, 1650, 3489, 9877, 8279, 9639, 907, 5671, 1527, 9154, 1184, 2876, 1344, 4770, 7751, 2807, 2900, 1551, 5166, 7744, 7927, 5161, 3474, 8465, 421, 8591, 2888, 644, 2592, 3535, 3613, 1237, 4645, 9492, 2538, 872, 9803, 7187, 5789, 104, 2878, 2493, 8828, 5526, 9977, 2164, 869, 7287, 1041, 3846, 8874, 3653, 4402, 5944, 3153, 6112, 2893, 1416, 4214, 7260, 2313, 3537, 147, 4820, 5492]

In [ ]:
mat = np.random.rand(5, 5)
x = open("data_float.txt", "w")
x.write(str(mat)) 
x.close()
!cat data_float.txt

[[0.03383209 0.5855969  0.68577528 0.6684733  0.42253028]
 [0.46423355 0.37230867 0.31287001 0.03226879 0.13664692]
 [0.52455628 0.26754557 0.77697765 0.94673258 0.73541886]
 [0.3373443  0.45535402 0.1753594  0.80170973 0.83739037]
 [0.23620458 0.81707856 0.97764038 0.21823009 0.47333314]]

In [ ]:
with open("data_float.txt", 'r') as infile, open("data_float.csv", 'w') as outfile:
        stripped = (line.strip() for line in infile)
        lines = (line.split(",") for line in stripped if line)
        writer = csv.writer(outfile)
        writer.writerows(lines)

!cat data_float.csv

[[0.03383209 0.5855969  0.68577528 0.6684733  0.42253028]
[0.46423355 0.37230867 0.31287001 0.03226879 0.13664692]
[0.52455628 0.26754557 0.77697765 0.94673258 0.73541886]
[0.3373443  0.45535402 0.1753594  0.80170973 0.83739037]
[0.23620458 0.81707856 0.97764038 0.21823009 0.47333314]]

# **Exercise 2**

In [ ]:
import json

In [ ]:
data = json.load(open('user_data.json'))
datafiltered = list(filter(lambda x: x['CreditCardType'] ==  "American Express", data))

[{'ID': '1', 'JobTitle': 'Project Manager', 'EmailAddress': 'Remy_Crawford1065@typill.biz', 'FirstNameLastName': 'Remy Crawford', 'CreditCard': '6205-7258-7671-0612', 'CreditCardType': 'Capital One'}, {'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}, {'ID': '3', 'JobTitle': 'Cook', 'EmailAddress': 'Russel_Hooper9403@bulaffy.com', 'FirstNameLastName': 'Russel Hooper', 'CreditCard': '6378-4461-8535-5847', 'CreditCardType': 'Discover'}, {'ID': '4', 'JobTitle': 'Business Broker', 'EmailAddress': 'Benjamin_Rowan6280@gembat.biz', 'FirstNameLastName': 'Benjamin Rowan', 'CreditCard': '5781-7635-1428-7414', 'CreditCardType': 'Discover'}, {'ID': '5', 'JobTitle': 'Loan Officer', 'EmailAddress': 'Matt_Lloyd3241@guentu.biz', 'FirstNameLastName': 'Matt Lloyd', 'CreditCard': '5771-8416-2736-1700', 'CreditCardType': 'Citibank'}, {'ID': '6', 'JobTitle': 'Cash Manager', 'EmailAddress': 'Domenic_Bell1507@brety.org', 'FirstNameLastName': 'Domenic Bell', 'CreditCard': '8025-0056-4707-1245', 'CreditCardType': 'MasterCard'}, {'ID': '7', 'JobTitle': 'Business Broker', 'EmailAddress': 'Harry_Kennedy245@gmail.com', 'FirstNameLastName': 'Harry Kennedy', 'CreditCard': '1422-4235-8541-1784', 'CreditCardType': 'MasterCard'}, {'ID': '8', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Christy_Emerson9521@supunk.biz', 'FirstNameLastName': 'Christy Emerson', 'CreditCard': '4763-6567-5460-0768', 'CreditCardType': 'Discover'}, {'ID': '9', 'JobTitle': 'Associate Professor', 'EmailAddress': 'Elly_Wright4017@jiman.org', 'FirstNameLastName': 'Elly Wright', 'CreditCard': '8364-4075-7278-4845', 'CreditCardType': 'Maestro'}, {'ID': '10', 'JobTitle': 'Treasurer', 'EmailAddress': 'Rufus_Lyon2653@twace.org', 'FirstNameLastName': 'Rufus Lyon', 'CreditCard': '8512-0806-3001-7570', 'CreditCardType': 'Bank of America'}, {'ID': '11', 'JobTitle': 'Production Painter', 'EmailAddress': 'Morgan_Young1920@acrit.org', 'FirstNameLastName': 'Morgan Young', 'CreditCard': '0031-6632-2223-4501', 'CreditCardType': 'MasterCard'}, {'ID': '12', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'Phillip_Carpenter9505@famism.biz', 'FirstNameLastName': 'Phillip Carpenter', 'CreditCard': '3657-0088-0820-5247', 'CreditCardType': 'American Express'}, {'ID': '13', 'JobTitle': 'Treasurer', 'EmailAddress': 'Ilona_Notman2221@grannar.com', 'FirstNameLastName': 'Ilona Notman', 'CreditCard': '6701-8641-8334-1664', 'CreditCardType': 'MasterCard'}, {'ID': '14', 'JobTitle': 'Food Technologist', 'EmailAddress': 'Laila_Ballard1579@twace.org', 'FirstNameLastName': 'Laila Ballard', 'CreditCard': '2610-4883-2454-8247', 'CreditCardType': 'Maestro'}, {'ID': '15', 'JobTitle': 'Mobile Developer', 'EmailAddress': 'Alexander_Radcliffe8448@gompie.com', 'FirstNameLastName': 'Alexander Radcliffe', 'CreditCard': '8500-5740-2860-5071', 'CreditCardType': 'Discover'}, {'ID': '16', 'JobTitle': 'Insurance Broker', 'EmailAddress': 'Lindsay_Speed8496@jiman.org', 'FirstNameLastName': 'Lindsay Speed', 'CreditCard': '8447-1205-1550-3637', 'CreditCardType': 'Citibank'}, {'ID': '17', 'JobTitle': 'Systems Administrator', 'EmailAddress': 'Logan_Umney9124@womeona.net', 'FirstNameLastName': 'Logan Umney', 'CreditCard': '2858-5205-5402-8268', 'CreditCardType': 'Maestro'}, {'ID': '18', 'JobTitle': 'Accountant', 'EmailAddress': 'Kamila_Stanley8141@vetan.org', 'FirstNameLastName': 'Kamila Stanley', 'CreditCard': '8045-1052-8885-1824', 'CreditCardType': 'Maestro'}, {'ID': '19', 'JobTitle': 'Production Painter', 'EmailAddress': 'Tania_Huggins911@fuliss.net', 'FirstNameLastName': 'Tania Huggins', 'CreditCard': '3730-0802-5148-6556', 'CreditCardType': 'Chase'}, {'ID': '20', 'JobTitle': 'Cook', 'EmailAddress': 'Domenic_Carter252@extex.org', 'FirstNameLastName': 'Domenic Carter', 'CreditCard': '2820-8547-1064-4183', 'CreditCardType': 'Discover'}, {'ID': '21', 'JobTitle': 'Audiologist', 'EmailAddress': 'Liv_Lane5399@bretoux.com', 'FirstNameLastName': 'Liv Lane', 'CreditCard': '5721-1200-6352-0432', 'CreditCardType': 'Visa'}, {'ID': '22', 'JobTitle': 'Staffing Consultant', 'EmailAddress': 'Gina_Overson5363@nimogy.biz', 'FirstNameLastName': 'Gina Overson', 'CreditCard': '2871-4456-3450-7544', 'CreditCardType': 'Citibank'}, {'ID': '23', 'JobTitle': 'Physician', 'EmailAddress': 'Tyson_Franks27@hourpy.biz', 'FirstNameLastName': 'Tyson Franks', 'CreditCard': '5222-3537-0581-5663', 'CreditCardType': 'UnionPay'}, {'ID': '24', 'JobTitle': 'Bookkeeper', 'EmailAddress': 'Rufus_Bentley4108@fuliss.net', 'FirstNameLastName': 'Rufus Bentley', 'CreditCard': '8138-0636-0065-7816', 'CreditCardType': 'UnionPay'}, {'ID': '25', 'JobTitle': 'Physician', 'EmailAddress': 'Jacqueline_Osmond1980@infotech44.tech', 'FirstNameLastName': 'Jacqueline Osmond', 'CreditCard': '1678-8088-8372-1615', 'CreditCardType': 'Discover'}, {'ID': '26', 'JobTitle': 'Banker', 'EmailAddress': 'Tania_Quinn6931@cispeto.com', 'FirstNameLastName': 'Tania Quinn', 'CreditCard': '8686-2013-7133-0063', 'CreditCardType': 'Discover'}, {'ID': '27', 'JobTitle': 'Fabricator', 'EmailAddress': 'Isabel_Redden1090@sheye.org', 'FirstNameLastName': 'Isabel Redden', 'CreditCard': '4857-0176-0370-6874', 'CreditCardType': 'Visa'}, {'ID': '28', 'JobTitle': 'Project Manager', 'EmailAddress': 'Russel_Graves1378@extex.org', 'FirstNameLastName': 'Russel Graves', 'CreditCard': '6718-4818-8011-6024', 'CreditCardType': 'American Express'}, {'ID': '29', 'JobTitle': 'Design Engineer', 'EmailAddress': 'Nicholas_Sylvester802@liret.org', 'FirstNameLastName': 'Nicholas Sylvester', 'CreditCard': '1305-6121-0676-2107', 'CreditCardType': 'UnionPay'}, {'ID': '30', 'JobTitle': 'Cashier', 'EmailAddress': 'Winnie_Gray7029@deavo.com', 'FirstNameLastName': 'Winnie Gray', 'CreditCard': '2153-6618-7375-1260', 'CreditCardType': 'Bank of America'}, {'ID': '31', 'JobTitle': 'Doctor', 'EmailAddress': 'Chelsea_Lucas5667@fuliss.net', 'FirstNameLastName': 'Chelsea Lucas', 'CreditCard': '3731-5883-8065-7803', 'CreditCardType': 'Capital One'}, {'ID': '32', 'JobTitle': 'HR Coordinator', 'EmailAddress': 'Analise_Weasley434@elnee.tech', 'FirstNameLastName': 'Analise Weasley', 'CreditCard': '8036-8876-3464-7777', 'CreditCardType': 'Maestro'}, {'ID': '33', 'JobTitle': 'Electrician', 'EmailAddress': 'Daphne_Rose2866@liret.org', 'FirstNameLastName': 'Daphne Rose', 'CreditCard': '2613-0861-0335-2612', 'CreditCardType': 'Citibank'}, {'ID': '34', 'JobTitle': 'Ambulatory Nurse', 'EmailAddress': 'Alan_Coll689@twace.org', 'FirstNameLastName': 'Alan Coll', 'CreditCard': '2358-6417-0170-6815', 'CreditCardType': 'Chase'}, {'ID': '35', 'JobTitle': 'Fabricator', 'EmailAddress': 'Agnes_Jennson1104@nickia.com', 'FirstNameLastName': 'Agnes Jennson', 'CreditCard': '4653-3251-8811-5468', 'CreditCardType': 'Citibank'}, {'ID': '36', 'JobTitle': 'Mobile Developer', 'EmailAddress': 'Daron_Tyrrell3117@corti.com', 'FirstNameLastName': 'Daron Tyrrell', 'CreditCard': '4602-3063-5462-4380', 'CreditCardType': 'Bank of America'}, {'ID': '37', 'JobTitle': 'CNC Operator', 'EmailAddress': 'Mary_Woodley2673@gembat.biz', 'FirstNameLastName': 'Mary Woodley', 'CreditCard': '2553-7085-1762-8352', 'CreditCardType': 'Wells Fargo'}, {'ID': '38', 'JobTitle': 'Web Developer', 'EmailAddress': 'Melania_Lee2367@mafthy.com', 'FirstNameLastName': 'Melania Lee', 'CreditCard': '6088-8850-2705-3210', 'CreditCardType': 'MasterCard'}, {'ID': '39', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Leanne_Newton1268@typill.biz', 'FirstNameLastName': 'Leanne Newton', 'CreditCard': '5438-0816-4166-4847', 'CreditCardType': 'American Express'}, {'ID': '40', 'JobTitle': 'Global Logistics Supervisor', 'EmailAddress': 'Henry_Oatway7245@bretoux.com', 'FirstNameLastName': 'Henry Oatway', 'CreditCard': '4065-6643-8160-8868', 'CreditCardType': 'Chase'}, {'ID': '41', 'JobTitle': 'Web Developer', 'EmailAddress': 'Nathan_Kirby4985@naiker.biz', 'FirstNameLastName': 'Nathan Kirby', 'CreditCard': '2670-6447-2566-1346', 'CreditCardType': 'Discover'}, {'ID': '42', 'JobTitle': 'Audiologist', 'EmailAddress': 'Caitlyn_Harris6055@tonsy.org', 'FirstNameLastName': 'Caitlyn Harris', 'CreditCard': '4131-3838-8715-7116', 'CreditCardType': 'Visa'}, {'ID': '43', 'JobTitle': 'Audiologist', 'EmailAddress': 'Ramon_Hunt6049@kideod.biz', 'FirstNameLastName': 'Ramon Hunt', 'CreditCard': '8225-4542-2136-6615', 'CreditCardType': 'Bank of America'}, {'ID': '44', 'JobTitle': 'IT Support Staff', 'EmailAddress': 'Kendra_Rowe9597@tonsy.org', 'FirstNameLastName': 'Kendra Rowe', 'CreditCard': '7537-4711-1276-5640', 'CreditCardType': 'UnionPay'}, {'ID': '45', 'JobTitle': 'Chef Manager', 'EmailAddress': 'Rowan_Shea1292@dionrab.com', 'FirstNameLastName': 'Rowan Shea', 'CreditCard': '4757-2183-5374-1642', 'CreditCardType': 'Visa'}, {'ID': '46', 'JobTitle': 'Doctor', 'EmailAddress': 'Ilona_Cox36@eirey.tech', 'FirstNameLastName': 'Ilona Cox', 'CreditCard': '0881-8168-5805-4286', 'CreditCardType': 'Wells Fargo'}, {'ID': '47', 'JobTitle': 'IT Support Staff', 'EmailAddress': 'Marissa_Amstead9020@atink.com', 'FirstNameLastName': 'Marissa Amstead', 'CreditCard': '1055-6387-0584-7138', 'CreditCardType': 'Discover'}, {'ID': '48', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Rebecca_Grey8444@typill.biz', 'FirstNameLastName': 'Rebecca Grey', 'CreditCard': '7715-7017-0032-3427', 'CreditCardType': 'Bank of America'}, {'ID': '49', 'JobTitle': 'CNC Operator', 'EmailAddress': 'Owen_Haines4054@bungar.biz', 'FirstNameLastName': 'Owen Haines', 'CreditCard': '8865-2460-2370-7520', 'CreditCardType': 'Discover'}, {'ID': '50', 'JobTitle': 'Associate Professor', 'EmailAddress': 'Selena_Steer3451@bulaffy.com', 'FirstNameLastName': 'Selena Steer', 'CreditCard': '4067-5448-8705-3230', 'CreditCardType': 'Wells Fargo'}, {'ID': '51', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Johnny_Hobbs6802@eirey.tech', 'FirstNameLastName': 'Johnny Hobbs', 'CreditCard': '1087-2434-3728-0607', 'CreditCardType': 'MasterCard'}, {'ID': '52', 'JobTitle': 'Cash Manager', 'EmailAddress': 'Hank_Lane5980@eirey.tech', 'FirstNameLastName': 'Hank Lane', 'CreditCard': '1506-8130-7417-4010', 'CreditCardType': 'Wells Fargo'}, {'ID': '53', 'JobTitle': 'Biologist', 'EmailAddress': 'David_Olson6310@liret.org', 'FirstNameLastName': 'David Olson', 'CreditCard': '5703-0573-0581-8012', 'CreditCardType': 'UnionPay'}, {'ID': '54', 'JobTitle': 'Production Painter', 'EmailAddress': 'Nina_Owen9489@gompie.com', 'FirstNameLastName': 'Nina Owen', 'CreditCard': '0207-1503-5346-5238', 'CreditCardType': 'Citibank'}, {'ID': '55', 'JobTitle': 'Clerk', 'EmailAddress': 'Matt_Adams3562@ovock.tech', 'FirstNameLastName': 'Matt Adams', 'CreditCard': '7254-2550-1362-1454', 'CreditCardType': 'Discover'}, {'ID': '56', 'JobTitle': 'Laboratory Technician', 'EmailAddress': 'Wade_Summers6636@brety.org', 'FirstNameLastName': 'Wade Summers', 'CreditCard': '1142-5310-6655-4588', 'CreditCardType': 'Visa'}, {'ID': '57', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Tony_Giles1960@iatim.tech', 'FirstNameLastName': 'Tony Giles', 'CreditCard': '8130-3425-7573-7745', 'CreditCardType': 'American Express'}, {'ID': '58', 'JobTitle': 'Systems Administrator', 'EmailAddress': 'Marvin_Gunn6317@corti.com', 'FirstNameLastName': 'Marvin Gunn', 'CreditCard': '5241-8630-7873-8114', 'CreditCardType': 'MasterCard'}, {'ID': '59', 'JobTitle': 'Paramedic', 'EmailAddress': 'Wade_Osman7248@sveldo.biz', 'FirstNameLastName': 'Wade Osman', 'CreditCard': '3554-3376-8561-1512', 'CreditCardType': 'Discover'}, {'ID': '60', 'JobTitle': 'Systems Administrator', 'EmailAddress': 'Nick_Andrews7603@deavo.com', 'FirstNameLastName': 'Nick Andrews', 'CreditCard': '8335-4304-1050-6575', 'CreditCardType': 'Citibank'}, {'ID': '61', 'JobTitle': 'Doctor', 'EmailAddress': 'Julius_Hudson3301@infotech44.tech', 'FirstNameLastName': 'Julius Hudson', 'CreditCard': '7622-3780-1820-8033', 'CreditCardType': 'Chase'}, {'ID': '62', 'JobTitle': 'CNC Operator', 'EmailAddress': 'Owen_Allcott5125@bauros.biz', 'FirstNameLastName': 'Owen Allcott', 'CreditCard': '4156-0107-7210-2630', 'CreditCardType': 'American Express'}, {'ID': '63', 'JobTitle': 'Systems Administrator', 'EmailAddress': 'Liliana_Carter7208@jiman.org', 'FirstNameLastName': 'Liliana Carter', 'CreditCard': '4002-5265-4505-1161', 'CreditCardType': 'MasterCard'}, {'ID': '64', 'JobTitle': 'Bookkeeper', 'EmailAddress': 'Marvin_Veale1904@vetan.org', 'FirstNameLastName': 'Marvin Veale', 'CreditCard': '2821-3462-2303-0744', 'CreditCardType': 'Capital One'}, {'ID': '65', 'JobTitle': 'Fabricator', 'EmailAddress': 'Caleb_Cassidy438@extex.org', 'FirstNameLastName': 'Caleb Cassidy', 'CreditCard': '1744-5780-8468-7044', 'CreditCardType': 'Capital One'}, {'ID': '66', 'JobTitle': 'Mobile Developer', 'EmailAddress': 'Mya_King2505@deavo.com', 'FirstNameLastName': 'Mya King', 'CreditCard': '2786-2161-3447-4455', 'CreditCardType': 'Capital One'}, {'ID': '67', 'JobTitle': 'Assistant Buyer', 'EmailAddress': 'Abbey_Flanders597@supunk.biz', 'FirstNameLastName': 'Abbey Flanders', 'CreditCard': '8125-3062-6276-1406', 'CreditCardType': 'UnionPay'}, {'ID': '68', 'JobTitle': 'Project Manager', 'EmailAddress': 'Liam_Lynn3280@kideod.biz', 'FirstNameLastName': 'Liam Lynn', 'CreditCard': '7152-3247-6053-2233', 'CreditCardType': 'American Express'}, {'ID': '69', 'JobTitle': 'Electrician', 'EmailAddress': 'Erick_Wellington505@irrepsy.com', 'FirstNameLastName': 'Erick Wellington', 'CreditCard': '7875-7615-4748-2157', 'CreditCardType': 'Chase'}, {'ID': '70', 'JobTitle': 'Global Logistics Supervisor', 'EmailAddress': 'Jamie_Gray9867@yahoo.com', 'FirstNameLastName': 'Jamie Gray', 'CreditCard': '5256-2237-5830-4507', 'CreditCardType': 'Capital One'}, {'ID': '71', 'JobTitle': 'Lecturer', 'EmailAddress': 'Logan_Michael1305@nickia.com', 'FirstNameLastName': 'Logan Michael', 'CreditCard': '5763-1350-7520-3532', 'CreditCardType': 'Citibank'}, {'ID': '72', 'JobTitle': 'Audiologist', 'EmailAddress': 'Nick_Morris6523@atink.com', 'FirstNameLastName': 'Nick Morris', 'CreditCard': '6450-1322-4742-5753', 'CreditCardType': 'Citibank'}, {'ID': '73', 'JobTitle': 'Biologist', 'EmailAddress': 'Zara_Kelly8902@eirey.tech', 'FirstNameLastName': 'Zara Kelly', 'CreditCard': '6764-1038-8026-1613', 'CreditCardType': 'Chase'}, {'ID': '74', 'JobTitle': 'Dentist', 'EmailAddress': 'Regina_Woodcock5820@yahoo.com', 'FirstNameLastName': 'Regina Woodcock', 'CreditCard': '0208-1753-3870-8002', 'CreditCardType': 'American Express'}, {'ID': '75', 'JobTitle': 'Clerk', 'EmailAddress': 'Logan_Anderson8354@muall.tech', 'FirstNameLastName': 'Logan Anderson', 'CreditCard': '2788-5607-2366-3240', 'CreditCardType': 'Chase'}, {'ID': '76', 'JobTitle': 'Web Developer', 'EmailAddress': 'Charlize_Benfield1039@bauros.biz', 'FirstNameLastName': 'Charlize Benfield', 'CreditCard': '8814-2858-7221-3376', 'CreditCardType': 'Visa'}, {'ID': '77', 'JobTitle': 'Web Developer', 'EmailAddress': 'Barney_Riley6813@vetan.org', 'FirstNameLastName': 'Barney Riley', 'CreditCard': '8632-3080-6254-5510', 'CreditCardType': 'Citibank'}, {'ID': '78', 'JobTitle': 'Business Broker', 'EmailAddress': 'Rick_Edwards9166@corti.com', 'FirstNameLastName': 'Rick Edwards', 'CreditCard': '6747-0304-6147-0185', 'CreditCardType': 'MasterCard'}, {'ID': '79', 'JobTitle': 'Lecturer', 'EmailAddress': 'Remy_Vaughan8074@twipet.com', 'FirstNameLastName': 'Remy Vaughan', 'CreditCard': '6617-5671-7115-1004', 'CreditCardType': 'Capital One'}, {'ID': '80', 'JobTitle': 'Insurance Broker', 'EmailAddress': 'Mavis_Flanders4645@iatim.tech', 'FirstNameLastName': 'Mavis Flanders', 'CreditCard': '4843-2145-7055-2347', 'CreditCardType': 'Chase'}, {'ID': '81', 'JobTitle': 'HR Specialist', 'EmailAddress': 'Carter_Wallace9614@atink.com', 'FirstNameLastName': 'Carter Wallace', 'CreditCard': '4256-7201-6717-4322', 'CreditCardType': 'American Express'}, {'ID': '82', 'JobTitle': 'Cook', 'EmailAddress': 'Vera_Avery8052@womeona.net', 'FirstNameLastName': 'Vera Avery', 'CreditCard': '1764-7042-1226-5002', 'CreditCardType': 'Bank of America'}, {'ID': '83', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Alexander_Huggins7943@deons.tech', 'FirstNameLastName': 'Alexander Huggins', 'CreditCard': '2460-4583-8540-8766', 'CreditCardType': 'Citibank'}, {'ID': '84', 'JobTitle': 'Cook', 'EmailAddress': 'Alma_Everett4997@acrit.org', 'FirstNameLastName': 'Alma Everett', 'CreditCard': '8330-6356-2615-0201', 'CreditCardType': 'Capital One'}, {'ID': '85', 'JobTitle': 'Global Logistics Supervisor', 'EmailAddress': 'Marvin_Reid7926@bretoux.com', 'FirstNameLastName': 'Marvin Reid', 'CreditCard': '3234-3554-1806-3082', 'CreditCardType': 'MasterCard'}, {'ID': '86', 'JobTitle': 'Staffing Consultant', 'EmailAddress': 'Brooklyn_Duvall6367@nimogy.biz', 'FirstNameLastName': 'Brooklyn Duvall', 'CreditCard': '5356-3431-8588-5071', 'CreditCardType': 'Wells Fargo'}, {'ID': '87', 'JobTitle': 'Electrician', 'EmailAddress': 'Chad_Mullins9299@twipet.com', 'FirstNameLastName': 'Chad Mullins', 'CreditCard': '7818-7020-6066-0813', 'CreditCardType': 'Wells Fargo'}, {'ID': '88', 'JobTitle': 'Project Manager', 'EmailAddress': 'Lucy_Latham3334@bretoux.com', 'FirstNameLastName': 'Lucy Latham', 'CreditCard': '7684-0613-7625-8222', 'CreditCardType': 'Wells Fargo'}, {'ID': '89', 'JobTitle': 'Inspector', 'EmailAddress': 'Dorothy_Gordon7252@guentu.biz', 'FirstNameLastName': 'Dorothy Gordon', 'CreditCard': '3582-4375-3185-8087', 'CreditCardType': 'Capital One'}, {'ID': '90', 'JobTitle': 'Systems Administrator', 'EmailAddress': 'David_Ring7929@mafthy.com', 'FirstNameLastName': 'David Ring', 'CreditCard': '7855-7234-8266-8574', 'CreditCardType': 'Maestro'}, {'ID': '91', 'JobTitle': 'Insurance Broker', 'EmailAddress': 'Mason_Lee7893@gmail.com', 'FirstNameLastName': 'Mason Lee', 'CreditCard': '3041-7301-0303-3203', 'CreditCardType': 'UnionPay'}, {'ID': '92', 'JobTitle': 'Staffing Consultant', 'EmailAddress': 'Maia_Stark2797@jiman.org', 'FirstNameLastName': 'Maia Stark', 'CreditCard': '3851-1403-1734-6321', 'CreditCardType': 'American Express'}, {'ID': '93', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'John_Richardson7481@iatim.tech', 'FirstNameLastName': 'John Richardson', 'CreditCard': '3771-4034-8432-8335', 'CreditCardType': 'Maestro'}, {'ID': '94', 'JobTitle': 'Bellman', 'EmailAddress': 'Ryan_Stewart9634@infotech44.tech', 'FirstNameLastName': 'Ryan Stewart', 'CreditCard': '7018-1875-7414-6004', 'CreditCardType': 'Wells Fargo'}, {'ID': '95', 'JobTitle': 'Baker', 'EmailAddress': 'Barney_Ebbs3496@deons.tech', 'FirstNameLastName': 'Barney Ebbs', 'CreditCard': '5114-5536-7367-8526', 'CreditCardType': 'UnionPay'}, {'ID': '96', 'JobTitle': 'Design Engineer', 'EmailAddress': 'Anthony_Welsch9633@jiman.org', 'FirstNameLastName': 'Anthony Welsch', 'CreditCard': '7137-8037-2575-2550', 'CreditCardType': 'Bank of America'}, {'ID': '97', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Ciara_Lomax982@bauros.biz', 'FirstNameLastName': 'Ciara Lomax', 'CreditCard': '3702-3440-2472-5424', 'CreditCardType': 'American Express'}, {'ID': '98', 'JobTitle': 'Webmaster', 'EmailAddress': 'Roger_Walsh3414@fuliss.net', 'FirstNameLastName': 'Roger Walsh', 'CreditCard': '1715-0341-7800-4452', 'CreditCardType': 'Chase'}, {'ID': '99', 'JobTitle': 'Bookkeeper', 'EmailAddress': 'Benny_Verdon7869@acrit.org', 'FirstNameLastName': 'Benny Verdon', 'CreditCard': '0568-6710-4464-2882', 'CreditCardType': 'MasterCard'}, {'ID': '100', 'JobTitle': 'IT Support Staff', 'EmailAddress': 'Logan_Booth1361@bulaffy.com', 'FirstNameLastName': 'Logan Booth', 'CreditCard': '8763-8068-8511-7223', 'CreditCardType': 'UnionPay'}, {'ID': '101', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Harry_Hall4872@cispeto.com', 'FirstNameLastName': 'Harry Hall', 'CreditCard': '2022-8687-3282-0601', 'CreditCardType': 'MasterCard'}, {'ID': '102', 'JobTitle': 'Ambulatory Nurse', 'EmailAddress': 'Michael_Jeffery206@deavo.com', 'FirstNameLastName': 'Michael Jeffery', 'CreditCard': '4570-7035-5853-4117', 'CreditCardType': 'Chase'}, {'ID': '103', 'Job

In [ ]:
pd.DataFrame(datafiltered).to_csv("/user_data.csv")

# **Exercise 3**

In [ ]:
import pandas as pd
datamush = pd.read_csv("mushrooms_categorized.csv")
print("Type: ",type(datamush))
print("length: ", len(datamush))
print("shape: ", datamush.shape)

Type:  <class 'pandas.core.frame.DataFrame'>
length:  8124
shape:  (8124, 23)

In [ ]:
print("head: \n", datamush.head())

head:
    class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1
1      0          5            2          9        1     0                1
2      0          0            2          8        1     3                1
3      1          5            3          8        1     6                1
4      0          5            2          3        0     5                1

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2
1             0          0           4  ...                         2
2             0          0           5  ...                         2
3             0          1           5  ...                         2
4             1          0           4  ...                         2

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2
1                       7                       7          0           2
2                       7                       7          0           2
3                       7                       7          0           2
4                       7                       7          0           2

   ring-number  ring-type  spore-print-color  population  habitat
0            1          4                  2           3        5
1            1          4                  3           2        1
2            1          4                  3           2        3
3            1          4                  2           3        5
4            1          0                  3           0        1

[5 rows x 23 columns]

In [ ]:
print("Tail: \n", datamush.tail())

Tail:
       class  cap-shape  cap-surface  cap-color  bruises  odor  \
8119      0          3            2          4        0     5
8120      0          5            2          4        0     5
8121      0          2            2          4        0     5
8122      1          3            3          4        0     8
8123      0          5            2          4        0     5

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
8119                0             0          0          11  ...
8120                0             0          0          11  ...
8121                0             0          0           5  ...
8122                1             0          1           0  ...
8123                0             0          0          11  ...

      stalk-surface-below-ring  stalk-color-above-ring  \
8119                         2                       5
8120                         2                       5
8121                         2                       5
8122                         1                       7
8123                         2                       5

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
8119                       5          0           1            1          4
8120                       5          0           0            1          4
8121                       5          0           1            1          4
8122                       7          0           2            1          0
8123                       5          0           1            1          4

      spore-print-color  population  habitat
8119                  0           1        2
8120                  0           4        2
8121                  0           1        2
8122                  7           4        2
8123                  4           1        2

[5 rows x 23 columns]

In [ ]:
datamush.groupby(['class']).mean()

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
class,,,,,,,,,,,,,,,,,,,,,
0,3.266160,1.615970,4.581749,0.653992,4.334601,0.954373,0.285171,0.068441,6.622624,0.615970,...,1.798479,6.098859,6.064639,0.0,1.931559,1.125475,3.007605,3.201521,3.283270,1.148289
1,3.436159,2.055158,4.421859,0.159346,3.940756,0.995403,0.028601,0.567926,2.863636,0.514811,...,1.394280,5.512768,5.504597,0.0,2.002043,1.009193,1.522983,4.021450,4.031665,1.895812

In [ ]:
datamush.to_json("/mushrooms_categorized.json")

# **Exercise 4**

In [ ]:
credits = pd.read_csv("credit_card.dat",header = None)
credits

                                                    0
0   1101111101101101001110001000001101011101101101...
1   1100111100101101011101111000001110001100101101...
2   1100101101111100101100101000001100001100001100...
3   1100001101101101101100011000001100111100001101...
4   1100001101001100111100101000001100011101101100...
5   1101011110001100101101111000001100101100001100...
6   1101011101111101111101001000001110001101011100...
7   1110001100011101001100001000001100011100101100...
8   1101011101111101101101001000001100011100011100...
9   1101101101001101011101101000001100011101111100...
10  1100011100101100101110001000001110001101101100...
11  1101111100001101011100011000001100001100011101...
12  1100001101101100011110001000001100111101011110...
13  1100011101011101001101011000001101011101001101...
14  1101101101111100111101011000001100111100011100...
15  1101111100101110001101111000001101011100001100...
16  1101111100001100111100111000001100101101101100...
17  1100101101011101101110001000001101011100101101...
18  1100011101101110001101001000001100101100101101...
19  1100001101101101111100101000001100101101011101...
20  1101101100111100111100101000001110001100111101...
21  1100011110001100011100111000001100111100111101...
22  1100101101001101111101111000001101101101001101...
23  1101011101011100011100101000001100111101011100...
24  1100111100001110001100111000001101111110001110...
25  1101001101011100101100011000001101011100011101...
26  1101111101011101101100111000001100111101101101...
27  1110001100111100101101001000001100101101101101...
28  1100001101011101101101011000001100101101011100...
29  1101011100011100001101111000001101011101011100...
30  1100101101001101101100101000001100011110001100...
31  1100101101111110001110001000001100001101101100...
32  1101011110001101011100011000001101011110001101...
33  1100001101101101111100001000001100011100001100...
34  1101011110001101111101001000001101011101011100...
35  1100101110001100001101011000001101011101001100...
36  1101011100001110001100111000001110001101001100...
37  1100011100001101111101101000001100011101001101...
38  1110001101001101001100001000001101001110001100...
39  1101001101111101011110001000001101101100011101...
40  1101111101011110001101101000001100001101101101...
41  1100101101011101001101001000001100011100101101...
42  1100111101001101111101001000001101011100001100...
43  1100011101001100011100001000001100001100101101...
44  1101111100111100011101011000001101001101001101...
45  1100001100101100101101001000001101111101111101...
46  1100001100011101111100001000001100101101111100...
47  1100101100001100001101101000001100101101001100...
48  1110001100011101001100101000001101001100001101...
49  1100111100001100101101101000001101111100111110...
50                                               1010

In [ ]:
creditnumbers = []
for i in credits[0]:
  listofcredit = []
  if i != "1010":
    for j in range(0,114,6):
      a = i[j:j+6]
      listofcredit.append(chr(int(a,2)))
      creditstr = ''.join(listofcredit)

    creditnumbers.append(creditstr)
    creditcard = ''.join(creditstr)

creditnumbers

['7648 5673 3775 2271',
 '3257 8247 3354 2266',
 '2722 0001 4011 6652',
 '0661 3063 3742 3150',
 '0432 1608 1462 4742',
 '5827 2027 8785 7303',
 '5774 8528 2087 1117',
 '8140 1210 6352 2845',
 '5764 1133 7301 7100',
 '6456 1737 4126 6726',
 '1228 8631 7382 0000',
 '7051 0160 5374 3166',
 '0618 3587 1630 6376',
 '1545 5454 7444 5636',
 '6735 3116 3202 6834',
 '7287 5011 1547 8413',
 '7033 2607 3328 4200',
 '2568 5244 1874 5024',
 '1684 2253 7570 7118',
 '0672 2576 0575 6631',
 '6332 8353 8787 1340',
 '1813 3361 1175 4211',
 '2477 6450 8840 2368',
 '5512 3505 2563 1326',
 '3083 7882 0621 0025',
 '4521 5148 8045 0334',
 '7563 3654 8713 5787',
 '8324 2664 0476 5561',
 '0565 2504 7168 3510',
 '5107 5507 1767 0738',
 '2462 1821 2448 1443',
 '2788 0638 6861 6554',
 '5851 5873 5474 0547',
 '0670 1004 4013 2655',
 '5874 5506 3048 0806',
 '2805 5401 8462 1260',
 '5083 8406 6310 1862',
 '1076 1445 3013 2266',
 '8440 4804 4844 5277',
 '4758 6141 0686 1387',
 '7586 0675 0315 2568',
 '2544 1258 7432 5165',
 '3474 5023 4434 5626',
 '1410 0270 0434 5086',
 '7315 4446 1104 4215',
 '0224 7742 8300 0266',
 '0170 2700 3145 0640',
 '2006 2437 8054 1600',
 '8142 4055 1776 0026',
 '3026 7380 1241 1084']

# **Exercise 5**